load("//web:defs.bzl", "wasm_build")

package(default_visibility = ["//visibility:public"])

wasm_build(
    name = "module",
    inputs = [
        "//examples/common:endpoint.h",
        "//core:sources",
        "//providers/sodium:sources",
        "//schema:sources",
        "//third_party/nanopb:sources",
        "//third_party/libsodium:headers",
    ],
    kind = "module",
    output = "device.mjs",
    persistent = True,
    sodium = "//web:sodium",
    sources = [
        "console.cpp",
        "//examples/common:endpoint.c",
        "//core:sc.c",
        "//providers/sodium:sc_sodium.c",
        "//schema:sc.pb.c",
        "//third_party/nanopb:pb_common.c",
        "//third_party/nanopb:pb_encode.c",
        "//third_party/nanopb:pb_decode.c",
    ],
)
