load("//build:defs.bzl", "py_binary", "py_test")

py_binary(
    name = "device_server_demo",
    data = [
        "//adapters/c:adapter",
        "//adapters/python:adapter",
        "//tests:coordinator.py",
    ],
    main = "device_server_demo.py",
    script_args = [
        "--device",
        "adapters/c/adapter",
        "--server",
        "adapters/python/adapter",
    ],
)

py_binary(
    name = "python_api",
    data = ["//bindings/python:simplecrypts.py"],
    main = "python_api.py",
    shared = "//providers/host:libsimplecrypts",
)

py_test(
    name = "production_api_test",
    data = ["//bindings/python:simplecrypts.py"],
    main = "python_api.py",
    shared = "//providers/host:libsimplecrypts",
)
