load("//build:defs.bzl", "py_binary", "py_test")
package(default_visibility = ["//visibility:public"])

py_binary(
    name = "console",
    main = "console.py",
    shared = "//providers/host:libsimplecrypts",
    data = ["//bindings/python:simplecrypts.py"],
)

py_test(
    name = "console_test",
    main = "console_test.py",
    shared = "//providers/host:libsimplecrypts",
    data = ["console.py", "//bindings/python:simplecrypts.py"],
)
