/* Generated by tools/resource_schema.py. */
#define SC_CREDITS_GROUP 1u
typedef struct {
 uint64_t issued;
 uint64_t consumed;
} sc_credits_1_values;
#define SC_CREDITS_ISSUED 1u
#define SC_CREDITS_CONSUMED 2u
static const sc_field_definition sc_credits_1_fields[]={
{1,1,2,1,0},
{2,1,1,1,0},
};
static const sc_group_definition sc_credits_groups[]={
{1,2,sc_credits_1_fields,sc_credit_validate},
};
static const sc_data_schema sc_credits_schema={{247,129,205,129,84,64,135,56,55,225,70,44,224,161,54,122,2,78,12,176,52,199,84,74,164,147,155,30,229,167,167,87},1,sc_credits_groups};
