/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "sc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(simplecrypts_Packet, simplecrypts_Packet, 2)


PB_BIND(simplecrypts_Record, simplecrypts_Record, 2)


PB_BIND(simplecrypts_GroupRecord, simplecrypts_GroupRecord, 2)



