/* Generated by tools/resource_schema.py. */
#define SC_EXAMPLE_GROUP 7u
typedef struct {
 uint64_t count;
 int64_t offset;
 uint8_t enabled;
 struct {uint8_t length;uint8_t bytes[16];} label;
 struct {uint8_t length;uint8_t bytes[16];} digest;
} sc_example_7_values;
#define SC_EXAMPLE_COUNT 1u
#define SC_EXAMPLE_OFFSET 2u
#define SC_EXAMPLE_ENABLED 3u
#define SC_EXAMPLE_LABEL 4u
#define SC_EXAMPLE_DIGEST 5u
static const sc_field_definition sc_example_7_fields[]={
{1,1,1,0,0},
{2,2,2,0,0},
{3,3,2,0,0},
{4,4,2,0,16},
{5,5,1,0,16},
};
#define SC_INDEPENDENT_GROUP 8u
typedef struct {
 uint8_t ready;
} sc_example_8_values;
#define SC_INDEPENDENT_READY 1u
static const sc_field_definition sc_example_8_fields[]={
{1,3,1,0,0},
};
static const sc_group_definition sc_example_groups[]={
{7,5,sc_example_7_fields,NULL},
{8,1,sc_example_8_fields,NULL},
};
static const sc_data_schema sc_example_schema={{156,73,144,135,141,83,187,32,229,106,206,73,124,194,252,170,50,254,228,136,23,144,22,114,57,167,87,82,254,201,239,133},2,sc_example_groups};
