#!/usr/bin/env python3
"""Generate bounded resource descriptors and language metadata; no dependencies."""

import argparse, hashlib, json, tempfile
from pathlib import Path

TYPES = {"uint64": 1, "int64": 2, "bool": 3, "text": 4, "bytes": 5}


def generate(path):
    s = json.loads(Path(path).read_text())
    groups = s["groups"]
    assert 0 < len(groups) <= 2
    digest = hashlib.sha256(json.dumps(s, sort_keys=True, separators=(",", ":")).encode()).digest()
    name = s["name"]
    lines = ["/* Generated by tools/resource_schema.py. */"]
    gids = set()
    for g in groups:
        assert 0 < g["id"] < 65536 and g["id"] not in gids
        gids.add(g["id"])
        assert 0 < len(g["fields"]) <= 5
        lines.append(f"#define SC_{g['name'].upper()}_GROUP {g['id']}u")
        lines.append("typedef struct {")
        for f in g["fields"]:
            typ = {"uint64": "uint64_t", "int64": "int64_t", "bool": "uint8_t"}.get(f["type"])
            lines.append(
                f" {typ} {f['name']};"
                if typ
                else f" struct {{uint8_t length;uint8_t bytes[{f['max_length']}];}} {f['name']};"
            )
        lines.append(f"}} sc_{name}_{g['id']}_values;")
        for f in g["fields"]:
            lines.append(f"#define SC_{g['name'].upper()}_{f['name'].upper()} {f['id']}u")
        lines.append(f"static const sc_field_definition sc_{name}_{g['id']}_fields[]={{")
        ids = set()
        size = 0
        for f in g["fields"]:
            assert 0 < f["id"] < 65536 and f["id"] not in ids
            ids.add(f["id"])
            t = TYPES[f["type"]]
            owner = {"device": 1, "server": 2}[f["owner"]]
            n = f.get("max_length", 0)
            assert 1 <= n <= 64 if t >= 4 else n == 0
            assert not f.get("monotonic") or t == 1
            size += 4 + (n if t >= 4 else 1 if t == 3 else 8)
            lines.append(f"{{{f['id']},{t},{owner},{int(f.get('monotonic', False))},{n}}},")
        assert size <= 160, "Group exceeds encrypted envelope payload bound"
        lines.append("};")
    lines.append(f"static const sc_group_definition sc_{name}_groups[]={{")
    for g in groups:
        lines.append(
            f"{{{g['id']},{len(g['fields'])},sc_{name}_{g['id']}_fields,{g.get('validator', 'NULL')}}},"
        )
    lines += [
        "};",
        f"static const sc_data_schema sc_{name}_schema={{{{{','.join(map(str, digest))}}},{len(groups)},sc_{name}_groups}};",
    ]
    return "\n".join(lines) + "\n", s


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    a = p.parse_args()
    for src, dest in [
        ("schema/resources.json", "schema/resources.h"),
        ("schema/test_resources.json", "schema/test_resources.h"),
    ]:
        code, s = generate(src)
        if a.check:
            assert Path(dest).read_text() == code, dest
        else:
            Path(dest).write_text(code)
        if src.endswith("/resources.json"):
            constants = {g["name"].upper(): g["id"] for g in s["groups"]}
            for g in s["groups"]:
                constants.update(
                    {(g["name"] + "_" + f["name"]).upper(): f["id"] for f in g["fields"]}
                )
            outputs = {
                "bindings/python/resources.py": "# Generated resource IDs\n"
                + "".join(f"{k} = {v}\n" for k, v in constants.items()),
                "bindings/rust/src/resources.rs": "// Generated resource IDs\n"
                + "".join(f"pub const {k}: u16 = {v};\n" for k, v in constants.items()),
                "bindings/go/resources.go": "// Generated resource IDs\npackage simplecrypts\n"
                + "".join(f"const {k} uint16 = {v}\n" for k, v in constants.items()),
                "web/resources.mjs": "// Generated resource metadata\nexport const resources="
                + json.dumps(s, separators=(",", ":"))
                + ";\n",
            }
            for path, content in outputs.items():
                if a.check:
                    assert Path(path).read_text() == content, path
                else:
                    Path(path).write_text(content)

    if a.check:
        original = json.loads(Path("schema/resources.json").read_text())
        bad = []
        wrong = json.loads(json.dumps(original))
        wrong["groups"][0]["fields"][0]["type"] = "text"
        wrong["groups"][0]["fields"][0]["max_length"] = 8
        bad.append(wrong)
        wrong = json.loads(json.dumps(original))
        wrong["groups"][0]["fields"] = [
            {"id": i + 1, "name": str(i), "type": "bytes", "owner": "device", "max_length": 64}
            for i in range(5)
        ]
        bad.append(wrong)
        wrong = json.loads(json.dumps(original))
        wrong["groups"][0]["fields"][1]["id"] = 1
        bad.append(wrong)
        for schema in bad:
            with tempfile.TemporaryDirectory() as tmp:
                path = Path(tmp) / "bad.json"
                path.write_text(json.dumps(schema))
                try:
                    generate(path)
                except (AssertionError, KeyError):
                    pass
                else:
                    raise AssertionError("Invalid resource schema accepted")
