import assert from 'node:assert/strict';
import {Lab,MAX_EVENTS} from './lab.mjs';
const l=new Lab();l.ready=true;l.queue=[{id:1,from:'device',to:'server',bytes:new Uint8Array([1,2,3]),corrupted:false}];l.nextPacket=2;
const copy=l.duplicate(1);l.corrupt(copy);assert.deepEqual([...l.packet(1).bytes],[1,2,3]);assert.deepEqual([...l.packet(copy).bytes],[1,2,2]);
for(let i=l.queue.length;i<64;i++)l.duplicate(1);
let called=false;l.command=async()=>{called=true;return {code:1};};await assert.rejects(()=>l.transmit('device'),/full/);assert(!called);assert.throws(()=>l.duplicate(1),/full/);
for(let i=0;i<1000;i++)l.event('event '+i);assert.equal(l.events.length,MAX_EVENTS);assert.equal(l.events[0].message,'event 800');
let cancelled=false;l.workers={device:{terminate(){cancelled=true;}}};l.pending.set(1,{reject(error){assert.equal(error.name,'AbortError');}});l.stop();assert(cancelled);assert.equal(l.pending.size,0);assert(!l.ready);
console.log('PASS relay: independent copies, queue/history bounds, no transmission at capacity, cancellation');
const r=new Lab();r.ready=true;r.states={device:{temperature:1},server:{temperature:1}};
r.queue=[{id:1,origin:1,location:'device-outbox',from:'device',to:'server',bytes:new Uint8Array([1,2,3]),corrupted:false}];r.nextPacket=2;
r.move(1,'relay');assert.equal(r.packet(1).location,'relay');let recipient;
r.command=async(role,command,args)=>{recipient=role;return {code:-3,status:'auth',state:{temperature:1}};};
const rejected=await r.deliver(1,'device');assert.equal(recipient,'device');assert.deepEqual(rejected.changes,[]);assert.equal(r.archive.length,1);assert.equal(r.queue.length,0);
const replay=r.replay(r.archive[0]);r.corrupt(replay);assert.deepEqual([...r.archive[0].bytes],[1,2,3]);r.drop(replay);
for(let i=0;i<30;i++){const id=r.replay(r.archive[0]);r.drop(id);}assert.equal(r.archive.length,16);
assert.throws(()=>r.move(999,'relay'),/no longer/);
console.log('PASS message board: holding, explicit recipients, rejection without changes, independent replay copies, bounded archive');
